name: Build PS4 Payload

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build payload
        uses: uses: Scene-Collective/ps4-payload-sdk@b732641
        with:
          app_path: .
          build_command: make

      - name: Upload payload
        uses: actions/upload-artifact@v4
        with:
          name: payloadbyKGtest
          path: |
            payloadbyKGtest.bin
            payload.elf
